export const mockNFTs = [
  {
    id: 1,
    name: "Cyber Ape #001",
    image: "/cosmic-warrior-nft.png",
    priceToOwn: "100 USDT",
    minRent: "1.5 USDT/day",
    currentProgress: 60,
    timeLeft: "3d 14h",
    competitors: 4,
    category: "Gaming",
    rentalStateId: "123ABC",
  },
  {
    id: 2,
    name: "Meta Helmet #045",
    image: "/cyberpunk-avatar-nft.png",
    priceToOwn: "120 USDT",
    minRent: "2.0 USDT/day",
    currentProgress: 35,
    timeLeft: "5d 8h",
    competitors: 2,
    category: "Art",
    rentalStateId: "123ABC",
  },
  {
    id: 3,
    name: "Digital Dreamscape",
    image: "/digital-dreamscape.png",
    priceToOwn: "75 USDT",
    minRent: "1.0 USDT/day",
    currentProgress: 82,
    timeLeft: "1d 12h",
    competitors: 6,
    category: "Art",
    rentalStateId: "123ABC",
  },
  {
    id: 4,
    name: "Quantum Crystal",
    image: "/quantum-crystal-nft.png",
    priceToOwn: "150 USDT",
    minRent: "2.5 USDT/day",
    currentProgress: 25,
    timeLeft: "6d 20h",
    competitors: 3,
    category: "Collectible",
    rentalStateId: "123ABC",
  },
  {
    id: 5,
    name: "Space Explorer",
    image: "/space-explorer-nft.png",
    priceToOwn: "90 USDT",
    minRent: "1.8 USDT/day",
    currentProgress: 67,
    timeLeft: "2d 16h",
    competitors: 5,
    category: "Gaming",
    rentalStateId: "123ABC",
  },
  {
    id: 6,
    name: "Neon Warrior",
    image: "/cosmic-warrior-nft.png",
    priceToOwn: "110 USDT",
    minRent: "1.7 USDT/day",
    currentProgress: 43,
    timeLeft: "4d 6h",
    competitors: 3,
    category: "Gaming",
    rentalStateId: "123ABC",
  },
];
